import type { GithubUser } from '../types/github';

export const mockProfiles: GithubUser[] = [
  {
    login: 'user1',
    id: 1,
    name: 'Alice Akira',
    avatar_url: 'https://avatars.githubusercontent.com/u/1',
    location: 'Tokyo',
    html_url: 'https://github.com/user1',
    public_repos: 12,
    followers: 120,
    following: 45,
    company: 'Acme Inc.',
  },
  {
    login: 'user2',
    id: 2,
    name: 'Benji Bakugo',
    avatar_url: 'https://avatars.githubusercontent.com/u/2',
    location: 'Osaka',
    html_url: 'https://github.com/user2',
    public_repos: 8,
    followers: 90,
    following: 32,
    company: null,
  },
  {
    login: 'user3',
    id: 3,
    name: 'Carla Chihiro',
    avatar_url: 'https://avatars.githubusercontent.com/u/3',
    location: 'Kyoto',
    html_url: 'https://github.com/user3',
    public_repos: 24,
    followers: 300,
    following: 88,
    company: 'GitGo',
  },
  {
    login: 'user4',
    id: 4,
    name: 'Daisuke Deno',
    avatar_url: 'https://avatars.githubusercontent.com/u/4',
    location: 'Fukuoka',
    html_url: 'https://github.com/user4',
    public_repos: 17,
    followers: 150,
    following: 54,
    company: null,
  },
  {
    login: 'user5',
    id: 5,
    name: 'Emi Ember',
    avatar_url: 'https://avatars.githubusercontent.com/u/5',
    location: 'Sapporo',
    html_url: 'https://github.com/user5',
    public_repos: 5,
    followers: 70,
    following: 22,
    company: 'StartupFox',
  },
  {
    login: 'user6',
    id: 6,
    name: 'Fujin Flynn',
    avatar_url: 'https://avatars.githubusercontent.com/u/6',
    location: 'Nagoya',
    html_url: 'https://github.com/user6',
    public_repos: 19,
    followers: 210,
    following: 67,
    company: null,
  },
  {
    login: 'user7',
    id: 7,
    name: 'Gina Genji',
    avatar_url: 'https://avatars.githubusercontent.com/u/7',
    location: 'Kobe',
    html_url: 'https://github.com/user7',
    public_repos: 13,
    followers: 130,
    following: 40,
    company: 'DevDrip',
  },
  {
    login: 'user8',
    id: 8,
    name: 'Hiro Hikari',
    avatar_url: 'https://avatars.githubusercontent.com/u/8',
    location: 'Sendai',
    html_url: 'https://github.com/user8',
    public_repos: 22,
    followers: 260,
    following: 78,
    company: 'Reactrix',
  },
  {
    login: 'user9',
    id: 9,
    name: 'Izumi Ion',
    avatar_url: 'https://avatars.githubusercontent.com/u/9',
    location: 'Nagano',
    html_url: 'https://github.com/user9',
    public_repos: 6,
    followers: 95,
    following: 33,
    company: null,
  },
  {
    login: 'user10',
    id: 10,
    name: 'Junko Jade',
    avatar_url: 'https://avatars.githubusercontent.com/u/10',
    location: 'Hiroshima',
    html_url: 'https://github.com/user10',
    public_repos: 10,
    followers: 110,
    following: 50,
    company: 'NodeNest',
  },
];
